/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'sample hardware' abstraction used by the samples at https://github.com/Azure/azure-sphere-samples.
// Some peripherals are on-board on the RDB, while other peripherals must be attached externally if needed.
// https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../azure_sphere_learning_path.json.  Do not edit it directly.

#pragma once
#include "mt3620_rdb.h"

// MT3620 RDB: Network Connected
#define CONNECTED_LED MT3620_RDB_NETWORKING_LED_RED

// MT3620 RDB: Grove Relay
#define RELAY MT3620_RDB_HEADER1_PIN4_GPIO

// CO2_ALERT
#define CO2_ALERT MT3620_RDB_HEADER1_PIN4_GPIO

// AVNET Start Kit Definition
#define I2C_CO2_SENSOR MT3620_RDB_HEADER2_ISU0_I2C

// MT3620 RDB: LED 1
#define LED_RED MT3620_RDB_LED1_RED

// MT3620 RDB: LED 1
#define LED_GREEN MT3620_RDB_LED1_GREEN

// MT3620 RDB: LED 1
#define LED_BLUE MT3620_RDB_LED1_BLUE

